default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: blogapp
  password: Incorrect12

development:
  adapter: postgresql
  database: BlogApp_Rails_development
  username: blogapp
  password: Incorrect12
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: BlogApp_Rails_test
  username: blogapp
  password: Incorrect12
  encoding: unicode
  host: localhost
  pool: 5

production:
  <<: *default
  database: BlogApp_Rails_production
  username: blogapp
  password: <%= ENV["BLOGAPP_RAILS_DATABASE_PASSWORD"] %>
